config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users
  resources :passwords, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:show, :index] do
    resources :lessons, only: [:create, :show, :update]
  end
  resources :words, only: [:index]

  namespace :admin do
    root "admins#home"

    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, except: [:show]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @activities = current_user.get_activity_items params
    else
      @categories = Category.all.paginate page: params[:page],
        per_page: Settings.category.number_per_page
    end
  end
end

app/views/static_pages/home.html.erb
<div class="login">
  <header>
    <h3><%= t "e_learning_system" %></h3>
  </header>
</div>
<% if logged_in? %>
  <div class="row">
    <div class="col s3">
      <div class="row">
        <div class="col s12">
          <div class="avatar">
            <%= show_avatar current_user %>
          </div>
        </div>
        <div class="col s12">
          <h5><%= current_user.fullname %></h5>
        </div>
      </div>
    </div>
    <div class="col s9">
      <div class="row">
        <div class="col s6 col-btn-header">
          <%= link_to t("list_word_title"), words_path, class: "btn-large waves-effect waves-light" %>
        </div>
        <div class="col s6 col-btn-header">
          <%= link_to t("lesson_title"), categories_path, class: "btn-large waves-effect waves-light" %>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <div class="login">
            <header>
              <h3>
                <%= t "activities" %>
              </h3>
            </header>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <%= render @activities %>
          <%= will_paginate @activities %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col s12">
      <%= render "categories/index_category" %>
    </div>
  </div>
<% end %>