config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users
  resources :passwords, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:show, :index] do
    resources :lessons, only: [:create, :show, :update]
  end
  resources :words, only: [:index]

  namespace :admin do
    root "admins#home"

    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, except: [:show]
  end
end

app/views/shared/_error_notice.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="card card-danger">
      <%= t("form_contain_error") + pluralize(object.errors.count, t("error")) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="choose-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_filter_form.html.erb
<%= form_for words_path, method: :get, remote: true do |f| %>
  <div class="input-field col s3">
    <%= select_tag :category_id,
      options_for_select(@categories.collect{|category| [category.title, category.id]},
      params[:category_id]), include_blank: t("all_category") %>
  </div>
  <% Settings.filter.each do |key, value| %>
    <div class="input-field col s3">
      <%= radio_button_tag :filter_params, value,
        checked = (params[:filter_params] == value) %>
      <%= label_tag "filter_params_#{value}", key %>
    </div>
  <% end %>
  <div class="input-field col s4">
    <%= f.submit t("submit_filter"), class: "btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/shared/_header.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper" id="my-navbar">
      <%= link_to t("e_learning_system"), root_path, class: "brand-logo" %>
      <ul class="right hide-on-med-and-down">
        <li>
          <%= link_to t("home"), root_path %>
        </li>
        <li>
          <%= link_to t("help"), "#" %>
        </li>
        <li>
          <%= link_to t("list_user"), users_path %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to current_user.fullname, current_user %>
          </li>
          <li>
            <%= link_to t("logout"), logout_path, method: :delete %>
          </li>
          <% if is_admin? %>
            <li>
              <%= link_to t("to_admin"), admin_root_path %>
            </li>
          <% end %>
        <% else %>
          <li>
            <%= link_to t("login"), login_path %>
          </li>
          <li>
            <%= link_to t("signup"), signup_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>