config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users
  resources :passwords, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:show, :index] do
    resources :lessons, only: [:create, :show, :update]
  end
  resources :words, only: [:index]

  namespace :admin do
    root "admins#home"

    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, except: [:show]
  end
end

app/views/admin/admins/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col s12">
      <div class="login">
        <header><%= t "admin_panel" %></header>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s4">
      <%= link_to t("new_category"), new_admin_category_path,
        class: "btn waves-effect waves-light" %>
    </div>
    <div class="col s4">
      <%= link_to t("list_categories"), admin_categories_path,
        class: "btn waves-effect waves-light" %>
    </div>
  </div>
  <div class="row">
    <div class="col s4">
      <%= link_to t("new_user_admin_link"), new_admin_user_path,
        class: "btn waves-effect waves-light" %>
    </div>
    <div class="col s4">
      <%= link_to t("list_user"), admin_users_path,
        class: "btn waves-effect waves-light" %>
    </div>
  </div>
</div>