config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "signup" => "users#new"
  post "signup" => "users#create"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users
  resources :passwords, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:show, :index] do
    resources :lessons, only: [:create, :show, :update]
  end
  resources :words, only: [:index]

  namespace :admin do
    root "admins#home"

    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, except: [:show]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: {minimum:9, maximum: 90}
  validates :description, presence: true, length: {minimum:9, maximum: 255}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminsController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "create_success"
      redirect_to :back
    else
      render :new
    end
  end

  def index
    @categories = Category.all.paginate page: params[:page],
      per_page: Settings.category.number_per_page
  end

  def destroy
    @category.lessons.each do |lesson|
      Activity.destroy_lesson(lesson, Settings.activities.learned).destroy_all
    end
    @category.destroy
    flash[:success] = t "category_delete_success"
    redirect_to :back
  end

  def show
    @word = Word.new
    Settings.word.number_of_answers.times do
      @word_answer = @word.word_answers.build
    end
    @words = @category.words.paginate page: params[:page],
      per_page: Settings.word.number_per_page
  end

  def edit

  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "update_success"
      redirect_to edit_admin_category_path @category
    else
      flash[:danger] = t "flash_error"
      render :edit
    end
  end

  private
  def category_params
    params.require(:category).permit :title, :description
  end

  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = "#{t "no_category_found"} #{params[:id]}"
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show]

  def show
    @words = @category.words.paginate page: params[:page],
      per_page: Settings.word.number_per_page
  end

  def index
    @categories = Category.all.paginate page: params[:page],
      per_page: Settings.category.number_per_page
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "no_category_found", id: params[:id]
      redirect_to root_path
    end
  end
end

app/views/categories/_category.html.erb
<tr>
  <td>
    <%= link_to category.title, category %>
  </td>
  <td>
    <%= link_to t("start_lesson"), category_lessons_path(category), method: :post,
      class: "btn waves-effect waves-light" %>
  </td>
</tr>

app/views/categories/_index_category.html.erb
<table class="striped">
  <thead>
    <tr>
      <th data-field="title"><%= t "category_title" %></th>
      <th data-field="option"><%= t "option" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @categories %>
  </tbody>
</table>
<%= will_paginate @categories %>

app/views/categories/index.html.erb
<div class="login">
  <header>
    <h3><%= t "list_categories" %></h3>
  </header>
</div>
<div class="row">
  <div class="col s12">
    <%= render "index_category" %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="col s5">
    <div class="card-panel teal">
      <span class="white-text">
        <h4>
          <%= @category.title %>
        </h4>
      </span>
    </div>
    <div class="card-panel teal">
      <span class="white-text">
        <h6>
          <%= @category.description %>
        </h6>
      </span>
    </div>
    <div class="card-panel">
      <span>
        <h6>
          <% if logged_in? %>
            <%= link_to t("start_lesson"), category_lessons_path(@category), method: :post,
              class: "btn waves-effect waves-light" %>
          <% else %>
            <%= link_to t("login_to_study"), login_path %>
          <% end %>
        </h6>
      </span>
    </div>
  </div>
  <div class="col s7">
    <div class="card-panel">
      <div class="login">
        <header><%= t "list_word_title" %></header>
        <div class="row">
          <div class="col s12">
            <%= render "words/index_word" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>